[settings]
lockfile = true

[tools]
node = "24"
usage = "2"
terraform = "1"
"npm:husky" = "9"
docker-cli = "29"
"github:cli/cli" = "2"
"npm:@commitlint/cli" = "20"
"github:hadolint/hadolint" = "2"
"npm:opencode-ai" = "1"
