[settings]
lockfile = true

[tasks.cd]
depends = ["release"]
file = "./.github/cd.sh"

[tasks.release]
depends = ["build"]
file = "./.github/release.sh"

[tasks.ci]
depends = ["format check", "danger ci", "test", "build"]
file = "./.github/ci.sh"

[tasks.danger]
file = "./.github/danger.sh"
