[settings]
lockfile = true

[tools]
node = "24"
npm = "11"

[tasks.test]
file = "./tasks/test.sh"

[tasks.build]
file = "./tasks/build.sh"

[tasks.format]
file = "./tasks/format.sh"

[tasks.update]
depends = "install"
file = "./tasks/update.sh"

[tasks.clean]
file = "./tasks/clean.sh"

[tasks.install]
file = "./tasks/install.sh"
