[settings]
lockfile = true

[tools]
usage = "2"
docker-cli = "latest"
"github:cli/cli" = "latest"
"github:hadolint/hadolint" = "latest"

[tasks.update]
depends = "install"
file = "./tasks/update.sh"

[tasks.clean]
file = "./tasks/clean.sh"
