[settings]
lockfile = true
experimental = true

[env]
GITHUB_ORG = "Duncan3142Org"
TEMPLATE_BRANCH = "TEMPLATE"

[tools]
node = "24"
npm = "11"
"npm:prettier" = "3"

[tasks.test]
file = "./tasks/test.sh"

[tasks.build]
file = "./tasks/build.sh"

[tasks.format]
file = "./tasks/format.sh"

[tasks.clean]
file = "./tasks/clean.sh"

[tasks.install]
file = "./tasks/install.sh"
