[settings]
lockfile = true

[tools]
node = "24"
npm = "11"
"npm:prettier" = "3"

[tasks.test]
file = "./tasks/test.sh"

[tasks.assets]
file = "./tasks/assets.sh"

[tasks.format]
file = "./tasks/format.sh"

[tasks.lint]
file = "./tasks/lint.sh"

[tasks.clean]
file = "./tasks/clean.sh"

[tasks.install]
file = "./tasks/install.sh"
