[tools]
"npm:semantic-release" = "25"
"npm:@semantic-release/changelog" = "6"
"npm:@semantic-release/git" = "10"

[tasks.cd]
depends = ["release"]
file = "./.github/cicd/cd.sh"

[tasks.release]
depends = ["build"]
file = "./.github/cicd/release.sh"
