name: CI

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review, labeled, unlabeled]
    branches: [main]
    paths:
      - "**"

concurrency:
  group: "CI"
  cancel-in-progress: true

permissions:
  pull-requests: write
  statuses: write
  contents: read
  packages: read

env:
  GITHUB_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_ENV: ci

jobs:
  ci:
    name: CI
    if: ${{ github.event.pull_request.state == 'open' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-22.04
    steps:
      - uses: jdx/mise-action@v3
      - uses: actions/checkout@v6
      - name: Install
        run: |
          mise run install
      - name: Danger
        uses: ./.github/actions/danger
      - name: CI
        run: |
          mise run ci
