name: Clone Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name"
        required: true
      confirm_repo_name:
        description: "Type the repository name again to confirm"
        required: true

concurrency:
  group: "Clone Repo"
  cancel-in-progress: false

env:
  MISE_ENV: admin

jobs:
  repo-mirror:
    environment: GitHubAdmin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.ADMIN_APP_ID }}
          private-key: ${{ secrets.ADMIN_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}
          permission-administration: write
          permission-contents: write
          permission-repository-custom-properties: write
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.ADMIN_TERRAFORM_API_TOKEN }}
      - uses: jdx/mise-action@v3
      - uses: ./.github/actions/clone-repo
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.inputs.repo_name }}
          confirm_repo_name: ${{ github.event.inputs.confirm_repo_name }}
      - uses: ./.github/actions/sync-settings
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.inputs.repo_name }}
