name: Sync Repo Settings

on:
  workflow_dispatch:

concurrency:
  group: "Sync Repo Settings"
  cancel-in-progress: false

jobs:
  repo-mirror:
    if: github.ref == 'refs/heads/main'
    environment: GitHubAdmin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.ADMIN_APP_ID }}
          private-key: ${{ secrets.ADMIN_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-administration: write
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.ADMIN_TERRAFORM_API_TOKEN }}
      - uses: ./.github/actions/sync-settings
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
